name: "PR Review"

on:
  pull_request_target:
    types: [edited, opened, reopened, synchronize]

jobs:
  pr_check:
    name: Check PR Target Branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check Target Branch
      run: |
        if [[ "${{ github.base_ref }}" != "MAKE-PRS-HERE" ]]; then
          echo "Please submit your PR to the 'MAKE-PRS-HERE' branch."
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git push origin --delete "${{ github.event.pull_request.head.ref }}"
          exit 1
        else
          echo "Thank you for submitting your PR to the correct branch!"
          echo "If you're not already in the FrogPilot Discord, please join via 'discord.FrogPilot.download'"
          echo "and feel free to @FrogsGoMoo and let me know you opened a PR!"
