name: "PR Review"

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  pr_check:
    name: Check PR Target Branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check Target Branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        if [[ "${{ github.base_ref }}" != "MAKE-PRS-HERE" ]]; then
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh pr comment ${{ github.event.pull_request.number }} --body "Please submit your pull request to the \"MAKE-PRS-HERE\" branch."

          gh pr close ${{ github.event.pull_request.number }}
          exit 1
        else
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh pr comment ${{ github.event.pull_request.number }} --body "Thank you for submitting your PR to the correct branch! If you're not already in the FrogPilot Discord, please join via 'discord.FrogPilot.download' and feel free to @FrogsGoMoo and let me know you opened a PR!"
        fi
