name: Compile FrogPilot
run-name: >-
  Compile ${{ inputs.publish_custom_branch ||
    inputs.publish_frogpilot && vars.BRANCH_RELEASE ||
    inputs.publish_staging && vars.BRANCH_STAGING ||
    inputs.publish_testing && vars.BRANCH_TESTING ||
    inputs.source_branch != 'Custom' && inputs.source_branch || inputs.custom_source_branch }}

on:
  workflow_dispatch:
    inputs:
      not_vetted:
        description: This branch is not vetted
        type: boolean
      source_branch:
        default: FrogPilot-Vetting
        description: Source branch
        options:
          - FrogPilot-Vetting
          - Custom
        type: choice
      custom_source_branch:
        description: Custom source branch
        type: string
      publish_frogpilot:
        description: Push to FrogPilot
        type: boolean
      publish_staging:
        description: Push to FrogPilot-Staging
        type: boolean
      publish_testing:
        description: Push to FrogPilot-Testing
        type: boolean
      publish_custom_branch:
        description: Custom target branch
        type: string
      runner:
        default: c3
        description: Select runner
        options: [c3, c3x]
        type: choice

env:
  PUBLIC_REPO: ${{ vars.PUBLIC_REPO }}

  GIT_EMAIL: ${{ vars.GIT_EMAIL }}
  GIT_NAME: ${{ vars.GIT_NAME }}

  BRANCH_RELEASE: ${{ vars.BRANCH_RELEASE }}
  BRANCH_STAGING: ${{ vars.BRANCH_STAGING }}
  BRANCH_TESTING: ${{ vars.BRANCH_TESTING }}
  CUSTOM_BRANCH: ${{ inputs.publish_custom_branch }}
  CUSTOM_SOURCE_BRANCH: ${{ inputs.custom_source_branch }}
  SOURCE_BRANCH: ${{ inputs.source_branch }}

  COMPILE_COMMIT: ${{ vars.COMPILE_COMMIT }}

permissions: {}

jobs:
  build_and_push:
    name: Compile FrogPilot
    runs-on: [self-hosted, "${{ inputs.runner }}"]
    steps:
      - name: Set up source
        run: |
          if [[ "$SOURCE_BRANCH" == "Custom" ]]; then
            SOURCE_BRANCH="$CUSTOM_SOURCE_BRANCH"
          fi

          sudo systemctl stop comma

          ssh_command="$(git -C /data/openpilot config --local --get core.sshCommand)"
          git clone --config core.sshCommand="$ssh_command" --filter=blob:none --no-tags --branch "$SOURCE_BRANCH" \
            "git@github.com:$GITHUB_REPOSITORY.git" "$RUNNER_TEMP/build"

          cd "$RUNNER_TEMP/build"
          git remote add public "$PUBLIC_REPO"
          git fetch --filter=blob:none --no-tags public

      - name: Build source
        env:
          BUILD: |
            source /etc/profile

            cd /data/openpilot
            export PYTHONPATH=/data/openpilot

            scons -j"$(nproc)" --minimal --ccflags=-g0 --cache-disable
        run: |
          sudo -E unshare --mount \
            sh -c 'mount --bind "$RUNNER_TEMP/build" /data/openpilot && exec setpriv --reuid="$SUDO_UID" --regid="$SUDO_GID" --init-groups bash -e -c "$BUILD"'

      - name: Prepare release
        run: |
          mkdir "$RUNNER_TEMP/release"
          mv "$RUNNER_TEMP/build/.git" "$RUNNER_TEMP/release"

          source /etc/profile
          python3 "$RUNNER_TEMP/build/release/prepare_release.py" "$RUNNER_TEMP/build" "$RUNNER_TEMP/release"

          cd "$RUNNER_TEMP/release"
          if ${{ inputs.publish_staging }} &&
             git rev-parse --verify --quiet "refs/remotes/public/$BRANCH_STAGING:.github/update_date" > /dev/null
          then
            git show "refs/remotes/public/$BRANCH_STAGING:.github/update_date" > .github/update_date
          fi

          if ${{ inputs.not_vetted }}; then
            touch not_vetted
          fi
          git add --all --force
          git -c user.name="$GIT_NAME" -c user.email="$GIT_EMAIL" \
            commit -m "$COMPILE_COMMIT"

      - name: Publish release
        env:
          WORKFLOW_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cd "$RUNNER_TEMP/release"
          git config credential.helper '!f() { printf "username=x-access-token\npassword=%s\n" "$WORKFLOW_TOKEN"; }; f'
          git config remote.public.pushurl "$PUBLIC_REPO"
          git config remote.origin.pushurl "https://github.com/$GITHUB_REPOSITORY.git"

          targets=()
          ${{ inputs.publish_frogpilot }} && targets+=("HEAD:refs/heads/$BRANCH_RELEASE")
          ${{ inputs.publish_staging }} && targets+=("HEAD:refs/heads/$BRANCH_STAGING")
          ${{ inputs.publish_testing }} && targets+=("HEAD:refs/heads/$BRANCH_TESTING")
          [[ -n "$CUSTOM_BRANCH" ]] && targets+=("HEAD:refs/heads/$CUSTOM_BRANCH")

          if (( ${#targets[@]} )); then
            git push --atomic --force-with-lease public "${targets[@]}"
          fi
          git push --force-with-lease origin HEAD

      - name: Start openpilot
        if: always()
        run: sudo systemctl start comma
