name: Merge FrogPilot into MAKE-PRS-HERE

on:
  push:
    branches:
      - FrogPilot

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Apply changes from FrogPilot to MAKE-PRS-HERE
        run: |
          git config user.name "FrogAi"
          git config user.email "91348155+FrogAi@users.noreply.github.com"
          git fetch origin
          git checkout MAKE-PRS-HERE
          git checkout FrogPilot -- .
          git commit -am "$(TZ="America/Phoenix" date +"%B %d, %Y Update")" || echo "No changes to commit"
          git push origin MAKE-PRS-HERE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
